site_name: Stendhal 1.49.5 Reference Documentation
site_description: A fun, friendly, & free multiplayer online adventure game.
copyright: Copyright Â© 2003-2026 Stendhal
site_url: https://stendhalgame.org/
nav:
  - Index: /reference/
  - Java: /reference/java/
  - TypeScript: /reference/typescript/
  - Lua: /reference/lua/
  - Home: /
extra_css:
  - css/objects.css
custom_theme:
  name: cinder
