name: Android Build Test

on:
  push:
    paths:
      - 'app/android/**'
  pull_request:
    paths:
      - 'app/android/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: job_info
        uses: daleyjem/gh-job-id@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: 'build'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build APKs with Ant
        uses: cedx/setup-ant@v6
        with:
          version: '1.10'
      - run: ant -noinput -buildfile build.xml android -Dgradle.params="assembleDebug assembleRelease"

      - name: Failure Report
        uses: sarisia/actions-status-discord@v1
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEVLOG }}
        with:
          title: 'Android Build Failed'
          description: '${{ steps.job_info.outputs.html_url }}'
